### ISSUE TITLE
CocoaPods spec with CGColorRef fix?

### ISSUE THREAD

**Issue by e28eta** [LordLobo/LLRoundSwitch#5]
Hi,

Can you please tag & submit a new spec to CocoaPods? We're trying to adopt LLRoundSwitch via CocoaPods and would like to have the fix for Issue #4.

Thanks,
Dan

**Comment by LordLobo** [comment]
I'll work on this tonight but a more realistic ETA might be Sunday or Monday.

**Comment by e28eta** [comment]
Great, thanks!

**Comment by zachwill** [comment]
Any chance you could just add a 1.0.1 tag, @LordLobo? I'll update the spec, but would just prefer to point to a tag versus a commit SHA.

**Comment by LordLobo** [comment]
Ok I should have 1.0.1 fixed in cocoapods and the default branch. Sorry it took me a bit longer to get to this, work spiked up more than was comfortable. So thanks for the reminder.

Let me know if you encounter any issues. I'm actually working on an 1.1.0 revision for use in a work project, but that might be a couple weeks away.

**Comment by e28eta** [comment]
Looks good, thanks
